### ISSUE TITLE
CancellationException: Could not pass event AsyncPlayerChatEvent to PwnFilter

### ISSUE THREAD

**Issue by mibby** [Pwn9/PwnFilter#26]
PwnFilter dev 125

Noticed this error in my logs when the server was in shutdown procedure, in the process of restarting.

```
[04:17:00] [Async Chat Thread - #6/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.2-SNAPSHOT-b125
java.util.concurrent.CancellationException
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[patched_1.10.2.jar:git-Paper-810]
    at com.pwn9.filter.bukkit.BukkitAPI.safeBukkitAPICall(BukkitAPI.java:117) ~[?:?]
    at com.pwn9.filter.bukkit.BukkitAPI.playerIdHasPermission(BukkitAPI.java:185) ~[?:?]
    at com.pwn9.filter.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:85) ~[?:?]
    at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.onPlayerChat(PwnFilterPlayerListener.java:69) ~[?:?]
    at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.lambda$activate$29(PwnFilterPlayerListener.java:133) ~[?:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-810]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-810]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-810]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.10.2.jar:git-Paper-810]
    at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1304) [patched_1.10.2.jar:git-Paper-810]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1219) [patched_1.10.2.jar:git-Paper-810]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.10.2.jar:git-Paper-810]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by mibby** [comment]
Still occurring rarely on shutdown. :(

```
[16:00:00] [Async Chat Thread - #131/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.2-SNAPSHOT-b125
java.util.concurrent.CancellationException
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[patched_1.10.2.jar:git-Paper-842]
	at com.pwn9.filter.bukkit.BukkitAPI.safeBukkitAPICall(BukkitAPI.java:117) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitAPI.playerIdHasPermission(BukkitAPI.java:185) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:85) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.onPlayerChat(PwnFilterPlayerListener.java:69) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.lambda$activate$29(PwnFilterPlayerListener.java:133) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-842]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-842]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-842]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.10.2.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1304) [patched_1.10.2.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1219) [patched_1.10.2.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.10.2.jar:git-Paper-842]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by mibby** [comment]
:(

```
[18:32:35] [Async Chat Thread - #67/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.2-SNAPSHOT-b125
java.util.concurrent.CancellationException
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[patched_1.10.2.jar:git-Paper-902]
	at com.pwn9.filter.bukkit.BukkitAPI.safeBukkitAPICall(BukkitAPI.java:117) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitAPI.playerIdHasPermission(BukkitAPI.java:185) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:85) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.onPlayerChat(PwnFilterPlayerListener.java:69) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.lambda$activate$29(PwnFilterPlayerListener.java:133) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-902]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-902]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-902]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.10.2.jar:git-Paper-902]
	at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1311) [patched_1.10.2.jar:git-Paper-902]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1226) [patched_1.10.2.jar:git-Paper-902]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.10.2.jar:git-Paper-902]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by mibby** [comment]
One day hopefully this error will be fixed. :(

```
[11:42:58] [Async Chat Thread - #20/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.2-SNAPSHOT-b125
java.util.concurrent.CancellationException
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[patched_1.11.2.jar:git-Paper-1029]
	at com.pwn9.filter.bukkit.BukkitAPI.safeBukkitAPICall(BukkitAPI.java:117) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitAPI.playerIdHasPermission(BukkitAPI.java:185) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:85) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.onPlayerChat(PwnFilterPlayerListener.java:69) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.lambda$activate$29(PwnFilterPlayerListener.java:133) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1029]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1029]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1029]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1299) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.11.2.jar:git-Paper-1029]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[11:42:58] [Async Chat Thread - #21/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.2-SNAPSHOT-b125
java.util.concurrent.CancellationException
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[patched_1.11.2.jar:git-Paper-1029]
	at com.pwn9.filter.bukkit.BukkitAPI.safeBukkitAPICall(BukkitAPI.java:117) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitAPI.playerIdHasPermission(BukkitAPI.java:185) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:85) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.onPlayerChat(PwnFilterPlayerListener.java:69) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.lambda$activate$29(PwnFilterPlayerListener.java:133) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1029]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1029]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1029]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1299) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [patched_1.11.2.jar:git-Paper-1029]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.11.2.jar:git-Paper-1029]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by mibby** [comment]
I'm guessing PwnFilter has been abandoned? :(

```
[10:02:57] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.2-SNAPSHOT-b125
java.util.concurrent.CancellationException: null
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[patched_1.12.jar:git-Paper-1111]
	at com.pwn9.filter.bukkit.BukkitAPI.safeBukkitAPICall(BukkitAPI.java:117) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitAPI.playerIdHasPermission(BukkitAPI.java:185) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:85) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.onPlayerChat(PwnFilterPlayerListener.java:69) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.lambda$activate$29(PwnFilterPlayerListener.java:133) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1339) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1254) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.jar:git-Paper-1111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by mibby** [comment]
One day. :(

```
[21:00:02] [Async Chat Thread - #63/ERROR]: Could not pass event AsyncPlayerChatEvent to PwnFilter v3.9.2-SNAPSHOT-b125
java.util.concurrent.CancellationException: null
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[patched_1.12.jar:git-Paper-1133]
	at com.pwn9.filter.bukkit.BukkitAPI.safeBukkitAPICall(BukkitAPI.java:117) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitAPI.playerIdHasPermission(BukkitAPI.java:185) ~[?:?]
	at com.pwn9.filter.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:85) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.onPlayerChat(PwnFilterPlayerListener.java:69) ~[?:?]
	at com.pwn9.filter.bukkit.listener.PwnFilterPlayerListener.lambda$activate$29(PwnFilterPlayerListener.java:133) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1339) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1254) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.jar:git-Paper-1133]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
