### ISSUE TITLE
Error on shutdown.

### ISSUE THREAD

**Issue by mibby** [Pwn9/PwnFilter#7]
Dev build 66. http://ci.toal.ca/job/PwnFilter/66/
```
[05:00:01] [Server thread/INFO]: [PwnFilter] Disabling PwnFilter v3.3.1-SNAPSHOT-b66
[05:00:01] [Server thread/ERROR]: Error occurred while disabling PwnFilter v3.3.1-SNAPSHOT-b66 (Is it up to date?)
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_20-ea]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_20-ea]
	at com.pwn9.PwnFilter.DataCache.stop(DataCache.java:106) ~[?:?]
	at com.pwn9.PwnFilter.PwnFilter.onDisable(PwnFilter.java:149) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[spigot.jar:git-Spigot-1486]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:348) [spigot.jar:git-Spigot-1486]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-1486]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-1486]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.disablePlugins(CraftServer.java:401) [spigot.jar:git-Spigot-1486]
	at net.minecraft.server.v1_7_R3.MinecraftServer.stop(MinecraftServer.java:392) [spigot.jar:git-Spigot-1486]
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-1486]
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1486]
```

**Comment by ptoal** [comment]
The latest Dev builds have done away with the old DataCache, and replaced it with something which I hope to me more efficient.  I don't see this happening anymore, so I'm going to close it.
